# https://docs.github.com/en/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2

updates:
  - package-ecosystem: "composer"

    directory: "/"

    schedule:
      interval: "weekly"
      day: "monday"
      time: "03:00"
      timezone: "Europe/Berlin"

    groups:
      # Specify a name for the group, which will be used in pull request titles
      # and branch names
      minor-patch-dependencies:
        # Define patterns to include dependencies in the group (based on
        # dependency name)
        patterns:
          - "*"
        # exclude-patterns:
        #   - "gc_ruboconfig"

    open-pull-requests-limit: 10

    reviewers:
      - "mimmi20"

    assignees:
      - "mimmi20"

    labels:
      - "dependencies"

    versioning-strategy: "increase"

    target-branch: "master"

    commit-message:
      include: "scope"
      prefix: "composer"

    ignore:
      - dependency-name: "laminas/laminas-diactoros"
        versions:
          - ">= 0"
#      - dependency-name: ergebnis/json-normalizer
#        versions:
#          - ">= 0"
#      - dependency-name: symfony/cache
#        versions:
#          - ">= 0"
#      - dependency-name: symfony/console
#        versions:
#          - ">= 0"
#      - dependency-name: symfony/yaml
#        versions:
#          - ">= 0"

  - package-ecosystem: "github-actions"

    directory: "/"

    schedule:
      interval: "weekly"
      day: "monday"
      time: "03:00"
      timezone: "Europe/Berlin"

    groups:
      # Specify a name for the group, which will be used in pull request titles
      # and branch names
      minor-patch-dependencies:
        # Define patterns to include dependencies in the group (based on
        # dependency name)
        patterns:
          - "*"
        # exclude-patterns:
        #   - "gc_ruboconfig"

    open-pull-requests-limit: 10

    reviewers:
      - "mimmi20"

    assignees:
      - "mimmi20"

    labels:
      - "dependencies"

    target-branch: "master"

    commit-message:
      prefix: "github-actions"
