template: |
  ## What’s Changed

  $CHANGES
tag-template: '$RESOLVED_VERSION'
version-resolver:
  major:
    labels:
      - 'major'
  minor:
    labels:
      - 'minor'
  patch:
    labels:
      - 'patch'
  default: patch
exclude-labels:
  - duplicate
  - question
  - invalid
  - wontfix
categories:
  - title: '**💥 Breaking:**'
    labels:
      - 'BC Break'
  - title: '**🍰 Enhancements:**'
    labels:
      - 'enhancement'
  - title: '**🐞 Bugs:**'
    labels:
      - 'bug'
  - title: '**💀 Deprecated:**'
    labels:
      - 'deprecated'
  - title: '**🗑 Removed:**'
    labels:
      - 'removed'
  - title: '**🛡 Security:**'
    labels:
      - 'security'
  - title: '**🕸 Dependencies:**'
    labels:
      - 'dependencies'
  - title: '**🧹 Maintenance:**'
    labels:
      - 'maintenance'
  # other Labels to mimmi20/browscap-helper-source
