name: Lock closed issue

on:
  issues:
    types: [closed]

permissions:
  actions: none
  checks: none
  contents: read
  deployments: none
  issues: read
  discussions: none
  packages: none
  pages: none
  pull-requests: read
  security-events: none
  statuses: none

jobs:
  lock:
    runs-on: ubuntu-latest
    steps:
      - uses: Dunning-Kruger/lock-issues@v1.1
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
